#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { registerValuationTools } from "./tools/valuation.js";
import { registerCreditTools } from "./tools/credit.js";
import { registerPETools } from "./tools/pe.js";
import { registerPortfolioTools } from "./tools/portfolio.js";
import { registerScenarioTools } from "./tools/scenarios.js";
import { registerMATools } from "./tools/ma.js";
import { registerJurisdictionTools } from "./tools/jurisdiction.js";
import { registerFixedIncomeTools } from "./tools/fixed_income.js";
import { registerDerivativesTools } from "./tools/derivatives.js";
import { registerThreeStatementTools } from "./tools/three_statement.js";
import { registerMonteCarloTools } from "./tools/monte_carlo.js";
import { registerQuantRiskTools } from "./tools/quant_risk.js";
import { registerRestructuringTools } from "./tools/restructuring.js";
import { registerRealAssetsTools } from "./tools/real_assets.js";
import { registerFxCommoditiesTools } from "./tools/fx_commodities.js";
import { registerSecuritizationTools } from "./tools/securitization.js";
import { registerVentureTools } from "./tools/venture.js";
import { registerEsgTools } from "./tools/esg.js";
import { registerRegulatoryTools } from "./tools/regulatory.js";
import { registerPrivateCreditTools } from "./tools/private_credit.js";
import { registerInsuranceTools } from "./tools/insurance.js";
import { registerFpaTools } from "./tools/fpa.js";
import { registerWealthTools } from "./tools/wealth.js";
import { registerCryptoTools } from "./tools/crypto.js";
import { registerMunicipalTools } from "./tools/municipal.js";
import { registerStructuredProductsTools } from "./tools/structured_products.js";
import { registerTradeFinanceTools } from "./tools/trade_finance.js";
import { registerCreditDerivativesTools } from "./tools/credit_derivatives.js";
import { registerConvertibleTools } from "./tools/convertibles.js";
import { registerLeaseAccountingTools } from "./tools/lease_accounting.js";
import { registerPensionTools } from "./tools/pension.js";
import { registerSovereignTools } from "./tools/sovereign.js";
import { registerRealOptionsTools } from "./tools/real_options.js";
import { registerEquityResearchTools } from "./tools/equity_research.js";
import { registerCommodityTradingTools } from "./tools/commodity_trading.js";
import { registerQuantStrategiesTools } from "./tools/quant_strategies.js";
import { registerTreasuryTools } from "./tools/treasury.js";
import { registerInfrastructureTools } from "./tools/infrastructure.js";
import { registerBehavioralTools } from "./tools/behavioral.js";
import { registerPerformanceAttributionTools } from "./tools/performance_attribution.js";
import { registerCreditPortfolioTools } from "./tools/credit_portfolio.js";
import { registerMacroEconomicsTools } from "./tools/macro_economics.js";
import { registerComplianceTools } from "./tools/compliance.js";
import { registerOnshoreStructuresTools } from "./tools/onshore_structures.js";
import { registerOffshoreStructuresTools } from "./tools/offshore_structures.js";
import { registerTransferPricingTools } from "./tools/transfer_pricing.js";
import { registerTaxTreatyTools } from "./tools/tax_treaty.js";
import { registerFatcaCrsTools } from "./tools/fatca_crs.js";
import { registerSubstanceRequirementsTools } from "./tools/substance_requirements.js";
import { registerRegulatoryReportingTools } from "./tools/regulatory_reporting.js";
import { registerAmlComplianceTools } from "./tools/aml_compliance.js";

const server = new McpServer({
  name: "corp-finance-mcp",
  version: "0.1.0",
});

registerValuationTools(server);
registerCreditTools(server);
registerPETools(server);
registerPortfolioTools(server);
registerScenarioTools(server);
registerMATools(server);
registerJurisdictionTools(server);
registerFixedIncomeTools(server);
registerDerivativesTools(server);
registerThreeStatementTools(server);
registerMonteCarloTools(server);
registerQuantRiskTools(server);
registerRestructuringTools(server);
registerRealAssetsTools(server);
registerFxCommoditiesTools(server);
registerSecuritizationTools(server);
registerVentureTools(server);
registerEsgTools(server);
registerRegulatoryTools(server);
registerPrivateCreditTools(server);
registerInsuranceTools(server);
registerFpaTools(server);
registerWealthTools(server);
registerCryptoTools(server);
registerMunicipalTools(server);
registerStructuredProductsTools(server);
registerTradeFinanceTools(server);
registerCreditDerivativesTools(server);
registerConvertibleTools(server);
registerLeaseAccountingTools(server);
registerPensionTools(server);
registerSovereignTools(server);
registerRealOptionsTools(server);
registerEquityResearchTools(server);
registerCommodityTradingTools(server);
registerQuantStrategiesTools(server);
registerTreasuryTools(server);
registerInfrastructureTools(server);
registerBehavioralTools(server);
registerPerformanceAttributionTools(server);
registerCreditPortfolioTools(server);
registerMacroEconomicsTools(server);
registerComplianceTools(server);
registerOnshoreStructuresTools(server);
registerOffshoreStructuresTools(server);
registerTransferPricingTools(server);
registerTaxTreatyTools(server);
registerFatcaCrsTools(server);
registerSubstanceRequirementsTools(server);
registerRegulatoryReportingTools(server);
registerAmlComplianceTools(server);

const transport = new StdioServerTransport();
await server.connect(transport);
