//! Emit `plugins/cfa-core/mcp/src/tools.ts` from parsed NAPI items.
//!
//! Mirrors `scripts/gen-mcp-tools.py`. The HEADER and FOOTER constants
//! contain the hand-written TypeScript runtime (passthrough schema,
//! profile telemetry, cfa_pipeline, cfa_assumptions, cfa_estimate_runtime,
//! cfa_profile). The middle section is generated from the NAPI item list:
//! a section comment per `// --- ... --- ` block, then one
//! `registerTool(...)` call per binding, followed by the legacy aliases.

use crate::data::descriptions;
use crate::parsers::napi::Item;

pub const HEADER: &str = r#"/**
 * cfa-core MCP tool registry.
 *
 * GENERATED FROM packages/bindings/src/lib.rs by scripts/gen-mcp-tools.py.
 * Do not edit by hand — re-run the generator if NAPI bindings change.
 *
 * Each entry registers one WASM export as an MCP tool. If a per-tool zod
 * schema exists in TOOL_SCHEMAS (generated by scripts/gen-zod-schemas.py),
 * it's used directly so Claude sees typed field hints. Otherwise we fall
 * back to the passthrough record schema and let Rust serde validate.
 *
 * Profile telemetry (T4.3): every tool call increments PROFILE counters
 * for call-count, total wall time, total compute time (from the Rust-side
 * `metadata.computation_time_us` field), and last-error string. Surfaced
 * via the `cfa_profile` MCP tool registered at the end of registerAllTools.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { TOOL_SCHEMAS } from "./schemas.js";

type WasmExports = Record<string, (json: string) => string>;

interface ToolStats {
  calls: number;
  errors: number;
  wall_us_total: number;
  compute_us_total: number;
  last_error?: string;
}

const PROFILE = new Map<string, ToolStats>();
const SESSION_STARTED_AT = Date.now();

function bumpProfile(
  name: string,
  wallUs: number,
  computeUs: number | null,
  errorMessage?: string,
) {
  let stats = PROFILE.get(name);
  if (!stats) {
    stats = { calls: 0, errors: 0, wall_us_total: 0, compute_us_total: 0 };
    PROFILE.set(name, stats);
  }
  stats.calls++;
  stats.wall_us_total += wallUs;
  if (computeUs !== null) stats.compute_us_total += computeUs;
  if (errorMessage) {
    stats.errors++;
    stats.last_error = errorMessage;
  }
}

function extractComputeUs(jsonResult: string): number | null {
  // Cheap regex parse — avoids JSON.parse cost for hot path. The Rust output
  // envelope always emits `"computation_time_us": <int>` inside metadata.
  const m = /"computation_time_us"\s*:\s*(\d+)/.exec(jsonResult);
  return m ? parseInt(m[1], 10) : null;
}

const passthroughShape = {
  input: z
    .record(z.any())
    .describe("Tool inputs as a JSON object — see tool description for fields"),
};

function wrap(jsonResult: string) {
  return { content: [{ type: "text" as const, text: jsonResult }] };
}

function shapeFor(name: string, exportName: string) {
  // Prefer the schema registered under the public tool name; fall back to the
  // underlying WASM export name (so legacy aliases inherit their target's schema).
  const schema = TOOL_SCHEMAS[name] ?? TOOL_SCHEMAS[exportName];
  if (schema) {
    return { input: schema };
  }
  return passthroughShape;
}

function registerTool(
  server: McpServer,
  wasm: WasmExports,
  name: string,
  description: string,
  exportName: string = name,
) {
  const fn = wasm[exportName];
  if (typeof fn !== "function") {
    // Defensive: WASM was built without this export. Skip with a warning so
    // partial WASM builds don't crash the whole server.
    console.warn(`[cfa-core] WASM export missing: ${exportName} — skipping`);
    return;
  }
  server.tool(
    name,
    description,
    shapeFor(name, exportName),
    async (params: { input: Record<string, unknown> }) => {
      const t0 = process.hrtime.bigint();
      try {
        const result = fn(JSON.stringify(params.input ?? {}));
        const wallUs = Number((process.hrtime.bigint() - t0) / 1000n);
        bumpProfile(name, wallUs, extractComputeUs(result));
        return wrap(result);
      } catch (err) {
        const wallUs = Number((process.hrtime.bigint() - t0) / 1000n);
        const message = err instanceof Error ? err.message : String(err);
        bumpProfile(name, wallUs, null, message);
        return {
          content: [{ type: "text" as const, text: `error: ${message}` }],
          isError: true,
        };
      }
    },
  );
}

// ---------------------------------------------------------------------------
// cfa_assumptions (T2.2): conversation-scoped key/value store
// ---------------------------------------------------------------------------

const ASSUMPTIONS = new Map<string, unknown>();

function registerAssumptionTools(server: McpServer) {
  server.tool(
    "cfa_set_assumption",
    "Store an assumption (rate, multiple, currency, scenario tag) in the conversation-scoped store. Persists across tool calls within one MCP session. Useful for 'use 8% WACC throughout this analysis' workflows where you don't want to re-state the value on every call. Reference from cfa_pipeline steps via $$.<key>.",
    {
      key: z.string().min(1).describe("Assumption name (e.g. 'wacc', 'tax_rate', 'forecast_currency')"),
      value: z.any().describe("Value to store. Decimals usually as strings; can also be number, boolean, array, object."),
    },
    async ({ key, value }) => {
      ASSUMPTIONS.set(key, value);
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify({ stored: { [key]: value }, total_assumptions: ASSUMPTIONS.size }, null, 2),
          },
        ],
      };
    },
  );

  server.tool(
    "cfa_get_assumptions",
    "Read all currently-stored conversation assumptions. Returns the full key/value map.",
    {},
    async () => {
      const out: Record<string, unknown> = {};
      for (const [k, v] of ASSUMPTIONS.entries()) out[k] = v;
      return {
        content: [{ type: "text" as const, text: JSON.stringify(out, null, 2) }],
      };
    },
  );

  server.tool(
    "cfa_clear_assumptions",
    "Clear the conversation assumption store. Useful when starting a new analysis with different inputs.",
    {
      keys: z
        .array(z.string())
        .optional()
        .describe("Specific keys to clear (default: clear all)"),
    },
    async ({ keys }) => {
      const cleared: string[] = [];
      if (keys && keys.length) {
        for (const k of keys) {
          if (ASSUMPTIONS.delete(k)) cleared.push(k);
        }
      } else {
        for (const k of ASSUMPTIONS.keys()) cleared.push(k);
        ASSUMPTIONS.clear();
      }
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify({ cleared, remaining: ASSUMPTIONS.size }, null, 2),
          },
        ],
      };
    },
  );
}

// ---------------------------------------------------------------------------
// cfa_pipeline (T2.1): atomic multi-step composition with shared state
// ---------------------------------------------------------------------------

interface PipelineStep {
  name: string;
  input?: Record<string, unknown>;
  save_as?: string;
}

interface PipelineResult {
  step: number;
  tool: string;
  saved_as?: string;
  result?: unknown;
  error?: string;
}

function resolveRef(value: unknown, state: Record<string, unknown>): unknown {
  if (typeof value === "string") {
    // $$.key → assumption store lookup (T2.2). Checked before $. so the longer
    // prefix wins.
    if (value.startsWith("$$.")) {
      const key = value.slice(3);
      if (!ASSUMPTIONS.has(key)) {
        throw new Error(`pipeline: unresolved assumption '${value}' (no such key in cfa_assumptions store)`);
      }
      return ASSUMPTIONS.get(key);
    }
    // $.var or $.var.field.subfield → step-output lookup
    if (value.startsWith("$.")) {
      const parts = value.slice(2).split(".");
      let current: unknown = state;
      for (const part of parts) {
        if (current && typeof current === "object" && part in (current as Record<string, unknown>)) {
          current = (current as Record<string, unknown>)[part];
        } else {
          throw new Error(`pipeline: unresolved reference '${value}' at path '.${part}'`);
        }
      }
      return current;
    }
  }
  if (Array.isArray(value)) {
    return value.map((v) => resolveRef(v, state));
  }
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) {
      out[k] = resolveRef(v, state);
    }
    return out;
  }
  return value;
}

function registerPipelineTool(server: McpServer, wasm: WasmExports) {
  server.tool(
    "cfa_pipeline",
    "Run a multi-step pipeline of cfa-core tools atomically with shared state. Each step can reference outputs of earlier steps via $.var.path JSONPath refs. Use save_as to bind a step's output to a variable. Reduces N round-trips through the LLM to 1 — useful for multi-step workflows like 'compute WACC, plug into DCF, then run sensitivity'.",
    {
      steps: z
        .array(
          z.object({
            name: z.string().describe("The cfa-core tool to call at this step"),
            input: z
              .record(z.any())
              .optional()
              .describe(
                "Tool inputs. String values starting with $. are resolved from prior steps' saved outputs.",
              ),
            save_as: z
              .string()
              .optional()
              .describe(
                "Bind this step's parsed JSON output to a variable name for later $. references",
              ),
          }),
        )
        .min(1)
        .describe("Ordered list of tool calls to execute"),
      stop_on_error: z
        .boolean()
        .optional()
        .describe(
          "Halt the pipeline at the first failed step (default true). When false, errors are recorded and execution continues.",
        ),
    },
    async (params) => {
      const stopOnError = params.stop_on_error ?? true;
      const state: Record<string, unknown> = {};
      const results: PipelineResult[] = [];

      for (let i = 0; i < params.steps.length; i++) {
        const step = params.steps[i] as PipelineStep;
        const stepNum = i + 1;
        try {
          const fn = wasm[step.name];
          if (typeof fn !== "function") {
            // Fall through — maybe it's a built-in like cfa_profile that we don't pipeline.
            throw new Error(`unknown WASM tool '${step.name}' (built-in tools cannot be pipelined)`);
          }
          const resolvedInput = step.input ? (resolveRef(step.input, state) as Record<string, unknown>) : {};
          const t0 = process.hrtime.bigint();
          const raw = fn(JSON.stringify(resolvedInput));
          const wallUs = Number((process.hrtime.bigint() - t0) / 1000n);
          const parsed = JSON.parse(raw);
          bumpProfile(step.name, wallUs, extractComputeUs(raw));
          if (step.save_as) {
            state[step.save_as] = parsed;
          }
          results.push({
            step: stepNum,
            tool: step.name,
            saved_as: step.save_as,
            result: parsed,
          });
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          results.push({ step: stepNum, tool: step.name, error: message });
          if (stopOnError) break;
        }
      }

      const summary = {
        steps_total: params.steps.length,
        steps_executed: results.length,
        steps_succeeded: results.filter((r) => !r.error).length,
        steps_failed: results.filter((r) => r.error).length,
        bound_variables: Object.keys(state),
        results,
      };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(summary, null, 2) }],
      };
    },
  );
}

// ---------------------------------------------------------------------------
// cfa_estimate_runtime (T2.3): runtime hints for expensive tools
//
// True MCP streaming requires Rust-side progress callbacks (refactoring
// run_monte_carlo, optimize_mean_variance, etc. to emit checkpoints across
// the WASM boundary). That's a v0.3 work item.
//
// What we can ship today: aggregate per-tool wall time stats from the
// PROFILE counter (T4.3) and let the LLM/user check expected duration
// before invoking. Keeps "don't run a 5-second tool 50 times in a
// sensitivity grid" feasible without true streaming.
// ---------------------------------------------------------------------------

// Hand-curated baseline expectations for tools we've benchmarked. Used when
// PROFILE has no data yet (cold-start session). Values in microseconds.
const RUNTIME_BASELINES: Record<string, { typical_us: number; max_us: number; notes?: string }> = {
  calculate_wacc: { typical_us: 500, max_us: 2_000 },
  build_dcf: { typical_us: 1_500, max_us: 5_000 },
  comps_analysis: { typical_us: 800, max_us: 3_000 },
  credit_metrics: { typical_us: 800, max_us: 3_000 },
  build_lbo: { typical_us: 3_000, max_us: 10_000 },
  run_monte_carlo: {
    typical_us: 500_000,
    max_us: 5_000_000,
    notes: "10k paths default. Scales linearly with `simulations` parameter. v0.3 will add streaming.",
  },
  run_mc_dcf: {
    typical_us: 800_000,
    max_us: 8_000_000,
    notes: "DCF with 10k Monte Carlo paths. Scales linearly with simulation count.",
  },
  optimize_mean_variance: {
    typical_us: 50_000,
    max_us: 500_000,
    notes: "Scales with universe size. >100 assets: expect >100ms.",
  },
  optimize_black_litterman_portfolio: {
    typical_us: 80_000,
    max_us: 1_000_000,
  },
  run_stress_test: { typical_us: 5_000, max_us: 50_000 },
  build_implied_vol_surface: {
    typical_us: 100_000,
    max_us: 2_000_000,
    notes: "Scales with strike × maturity grid size.",
  },
  calibrate_sabr: {
    typical_us: 200_000,
    max_us: 5_000_000,
    notes: "Iterative calibration; convergence depends on initial guess.",
  },
};

function registerEstimateTool(server: McpServer) {
  server.tool(
    "cfa_estimate_runtime",
    "Estimate the wall time a cfa-core tool will take before you invoke it. Combines hand-curated baselines with this session's measured PROFILE data (T4.3). Returns typical/max microseconds plus a recommendation (run normally / batch / split). Use before iterating an expensive tool in a loop.",
    {
      tool: z.string().describe("Tool name to estimate"),
      iterations: z
        .number()
        .int()
        .min(1)
        .optional()
        .describe("Planned iteration count (e.g. for sensitivity grids). Default 1."),
    },
    async ({ tool, iterations = 1 }) => {
      const measured = PROFILE.get(tool);
      const baseline = RUNTIME_BASELINES[tool];

      let typical_us: number;
      let max_us: number;
      let source: string;

      if (measured && measured.calls >= 3) {
        typical_us = Math.round(measured.wall_us_total / measured.calls);
        max_us = typical_us * 3;
        source = `measured (${measured.calls} calls this session)`;
      } else if (baseline) {
        typical_us = baseline.typical_us;
        max_us = baseline.max_us;
        source = "hand-curated baseline";
      } else {
        typical_us = 5_000;
        max_us = 50_000;
        source = "default estimate (no baseline or measurement)";
      }

      const total_typical_us = typical_us * iterations;
      const total_max_us = max_us * iterations;

      let recommendation = "run normally";
      if (total_max_us > 30_000_000) {
        recommendation =
          "split into multiple invocations; total max exceeds 30s, may hit MCP timeouts";
      } else if (total_typical_us > 5_000_000) {
        recommendation =
          "consider running in background; expected wall >5s. v0.3 will support streaming for tools with this signature.";
      } else if (total_typical_us > 500_000) {
        recommendation = "OK but slow; consider caching results across iterations";
      }

      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(
              {
                tool,
                iterations,
                source,
                per_call: { typical_us, max_us },
                total: {
                  typical_us: total_typical_us,
                  max_us: total_max_us,
                  typical_ms: Math.round(total_typical_us / 1000),
                  max_ms: Math.round(total_max_us / 1000),
                },
                recommendation,
                notes: baseline?.notes,
              },
              null,
              2,
            ),
          },
        ],
      };
    },
  );
}

function registerProfileTool(server: McpServer) {
  server.tool(
    "cfa_profile",
    "Per-session telemetry: call counts, total wall time, total Rust compute time, and overhead per tool. Returns the top-N by total wall time. Useful before iterating an expensive tool (e.g. monte_carlo_dcf) in a sensitivity grid.",
    {
      top: z
        .number()
        .int()
        .min(1)
        .max(500)
        .optional()
        .describe("Maximum number of tools to report (default: 20, sorted by total wall time desc)"),
      sort_by: z
        .enum(["wall", "compute", "calls", "overhead"])
        .optional()
        .describe("Sort key (default: wall)"),
    },
    async (params) => {
      const top = params.top ?? 20;
      const sort = params.sort_by ?? "wall";
      const entries = Array.from(PROFILE.entries()).map(([name, s]) => ({
        tool: name,
        calls: s.calls,
        errors: s.errors,
        wall_us_total: s.wall_us_total,
        compute_us_total: s.compute_us_total,
        overhead_us_total: Math.max(0, s.wall_us_total - s.compute_us_total),
        avg_wall_us: s.calls ? Math.round(s.wall_us_total / s.calls) : 0,
        avg_compute_us: s.calls ? Math.round(s.compute_us_total / s.calls) : 0,
        last_error: s.last_error,
      }));
      const sortKey: Record<typeof sort, (e: typeof entries[number]) => number> = {
        wall: (e) => e.wall_us_total,
        compute: (e) => e.compute_us_total,
        calls: (e) => e.calls,
        overhead: (e) => e.overhead_us_total,
      };
      entries.sort((a, b) => sortKey[sort](b) - sortKey[sort](a));
      const report = {
        session_uptime_ms: Date.now() - SESSION_STARTED_AT,
        unique_tools_called: entries.length,
        total_calls: entries.reduce((acc, e) => acc + e.calls, 0),
        total_errors: entries.reduce((acc, e) => acc + e.errors, 0),
        sort_by: sort,
        top: entries.slice(0, top),
      };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(report, null, 2) }],
      };
    },
  );
}

export function registerAllTools(server: McpServer, wasm: WasmExports): number {
  let count = 0;
"#;

pub const FOOTER: &str = r#"
  // --- Built-in: cfa_assumptions (T2.2 conversation-scoped store) ---
  registerAssumptionTools(server); count += 3;

  // --- Built-in: cfa_pipeline (T2.1 composition) ---
  registerPipelineTool(server, wasm); count++;

  // --- Built-in: cfa_estimate_runtime (T2.3 runtime hints) ---
  registerEstimateTool(server); count++;

  // --- Built-in: cfa_profile (T4.3 telemetry) ---
  registerProfileTool(server); count++;

  return count;
}
"#;

/// Capitalise the first letter; rest stays as-is. Matches Python `str.capitalize()`
/// behaviour with snake-cased input being a lower-cased token stream where
/// only the first char becomes uppercase.
fn humanise(name: &str) -> String {
    // Python: name.replace("_", " ").capitalize()
    // capitalize() lowercases everything then upper-cases the first char.
    let lowered = name.replace('_', " ").to_lowercase();
    let mut chars = lowered.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Render the body that goes between HEADER and FOOTER: section comments,
/// `registerTool(...)` lines, and the legacy alias block.
pub fn emit(items: &[Item]) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str(HEADER);

    let mut current_section = String::from("Uncategorised");
    let skip_set: std::collections::HashSet<&str> = descriptions::SKIP.iter().copied().collect();

    for item in items {
        match item {
            Item::Section(s) => {
                current_section = s.title.clone();
                out.push_str(&format!("\n  // --- {} ---\n", s.title));
            }
            Item::Tool(t) => {
                if skip_set.contains(t.name.as_str()) {
                    continue;
                }
                let description = match descriptions::lookup(&t.name) {
                    Some(d) => d.to_string(),
                    None => format!("{}: {}.", current_section, humanise(&t.name)),
                };
                let escaped = escape_template_literal(&description);
                out.push_str(&format!(
                    "  registerTool(server, wasm, \"{}\", `{}`); count++;\n",
                    t.name, escaped
                ));
            }
        }
    }

    // Legacy aliases are a constant slice today, but keep the conditional
    // for parity with the Python control flow (Python: `if LEGACY_ALIASES:`).
    #[allow(clippy::const_is_empty)]
    if !descriptions::LEGACY_ALIASES.is_empty() {
        out.push_str(
            "\n  // --- Legacy v0.1 aliases (kept for skill/command compatibility) ---\n",
        );
        for (alias, target) in descriptions::LEGACY_ALIASES {
            // Same fallback chain as Python:
            // overrides[alias] -> overrides[target] -> "Alias for <target>".
            let description = match descriptions::lookup(alias) {
                Some(d) => d.to_string(),
                None => match descriptions::lookup(target) {
                    Some(d) => d.to_string(),
                    None => format!("Alias for {}", target),
                },
            };
            let escaped = escape_template_literal(&description);
            out.push_str(&format!(
                "  registerTool(server, wasm, \"{}\", `{}`, \"{}\"); count++;\n",
                alias, escaped, target
            ));
        }
    }

    out.push_str(FOOTER);
    out
}

/// Escape a description for embedding inside a TS backtick template literal.
/// Order: backslashes first, then backticks. Matches Python:
///   esc = description.replace("\\", "\\\\").replace("`", "\\`")
fn escape_template_literal(s: &str) -> String {
    s.replace('\\', "\\\\").replace('`', "\\`")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn humanise_matches_python_capitalize() {
        assert_eq!(humanise("calculate_wacc"), "Calculate wacc");
        assert_eq!(humanise("price_bond"), "Price bond");
        assert_eq!(humanise("ALREADY_UPPER"), "Already upper");
    }

    #[test]
    fn escapes_template_literal_chars() {
        assert_eq!(escape_template_literal("a`b"), "a\\`b");
        assert_eq!(escape_template_literal(r"a\b"), r"a\\b");
        // Order matters: backslash before backtick.
        assert_eq!(escape_template_literal(r"a\`b"), r"a\\\`b");
    }
}
