/* auto-generated by napi-rs */
/* eslint-disable */

/** Valuation: Weighted Average Cost of Capital */
export function calculateWacc(inputJson: string): string;

/** Valuation: Discounted Cash Flow model */
export function buildDcf(inputJson: string): string;

/** Valuation: Comparable company analysis */
export function compsAnalysis(inputJson: string): string;

/** Credit: Full suite of credit metrics with synthetic rating */
export function creditMetrics(inputJson: string): string;

/** Credit: Debt capacity analysis */
export function debtCapacity(inputJson: string): string;

/** Credit: Covenant compliance testing */
export function covenantCompliance(inputJson: string): string;

/** PE: IRR, XIRR, MOIC, Cash-on-Cash returns */
export function calculateReturns(inputJson: string): string;

/** PE: Amortisation / debt paydown schedule */
export function buildDebtSchedule(inputJson: string): string;

/** PE: Sources and uses of funds table */
export function sourcesAndUses(inputJson: string): string;

/** Portfolio: Risk-adjusted return metrics (Sharpe, Sortino, etc.) */
export function riskAdjustedReturns(inputJson: string): string;

/** Portfolio: VaR, CVaR, drawdown, and other risk metrics */
export function riskMetrics(inputJson: string): string;

/** Portfolio: Kelly criterion position sizing */
export function kellySizing(inputJson: string): string;

/** Scenarios: Two-dimensional sensitivity grid */
export function buildSensitivityGrid(inputJson: string): string;

/** Scenarios: Multi-scenario weighted analysis */
export function scenarioAnalysis(inputJson: string): string;
