import { z } from "zod";

export const PppModelSchema = z.object({
  project_name: z.string().describe("Project name / identifier"),
  total_capex: z.coerce.number().positive().describe("Total construction cost"),
  construction_period_months: z.coerce.number().int().min(0).describe("Construction duration in months"),
  concession_years: z.coerce.number().int().positive().describe("Total concession period in years (including construction)"),
  revenue_model: z.enum(["AvailabilityPayment", "DemandBased", "Mixed"]).describe("Revenue model type"),
  annual_availability_payment: z.coerce.number().describe("Annual availability payment (if availability-based)"),
  initial_traffic_volume: z.coerce.number().describe("Initial traffic volume per year (if demand-based)"),
  traffic_growth_rate: z.coerce.number().describe("Annual demand growth rate (decimal, e.g. 0.03 = 3%)"),
  toll_rate: z.coerce.number().describe("Price per unit of demand (toll rate)"),
  opex_pct_revenue: z.coerce.number().describe("Operating costs as percentage of revenue"),
  major_maintenance_reserve_pct: z.coerce.number().describe("Annual major maintenance reserve as percentage of capex"),
  senior_debt_pct: z.coerce.number().describe("Percentage of capex funded by senior debt"),
  senior_debt_rate: z.coerce.number().min(0).describe("Interest rate on senior debt"),
  senior_debt_tenor_years: z.coerce.number().int().min(0).describe("Senior debt maturity in years"),
  mezzanine_debt_pct: z.coerce.number().describe("Percentage of capex funded by mezzanine debt (can be 0)"),
  mezzanine_rate: z.coerce.number().describe("Mezzanine debt interest rate"),
  equity_pct: z.coerce.number().describe("Equity contribution percentage"),
  tax_rate: z.coerce.number().describe("Corporate tax rate"),
  discount_rate: z.coerce.number().describe("Discount rate for NPV calculations"),
  inflation_rate: z.coerce.number().describe("Annual inflation rate for escalation"),
  availability_deductions_pct: z.coerce.number().describe("Expected deductions for underperformance (% of availability payment)"),
  lifecycle_cost_schedule: z.array(z.coerce.number()).optional().describe("Major lifecycle costs by year (index 0 = year 1 of operations)"),
});

export const ConcessionSchema = z.object({
  concession_name: z.string().describe("Concession name / identifier"),
  remaining_years: z.coerce.number().int().positive().describe("Years remaining on the concession"),
  current_annual_revenue: z.coerce.number().min(0).describe("Current annual revenue"),
  revenue_growth_rate: z.coerce.number().describe("Annual revenue growth rate (decimal, e.g. 0.03 = 3%)"),
  opex_margin: z.coerce.number().describe("Opex as percentage of revenue"),
  capex_maintenance: z.coerce.number().describe("Annual maintenance capex"),
  handback_cost: z.coerce.number().describe("Cost of handback condition compliance"),
  handback_years_before_end: z.coerce.number().int().min(0).describe("Years before end when handback capex starts"),
  discount_rate: z.coerce.number().describe("WACC for NPV calculations"),
  terminal_value_approach: z.string().describe("Terminal value approach: 'None', 'Reversion', or 'Extension'"),
  reversion_value: z.coerce.number().describe("Reversion value (if terminal approach is 'Reversion')"),
  extension_probability: z.coerce.number().describe("Probability of extension (decimal, e.g. 0.50 = 50%)"),
  extension_years: z.coerce.number().int().min(0).describe("Additional years if extension granted"),
  outstanding_debt: z.coerce.number().describe("Outstanding debt balance"),
  debt_rate: z.coerce.number().describe("Debt interest rate"),
  annual_debt_service: z.coerce.number().describe("Annual debt service (principal + interest)"),
  tax_rate: z.coerce.number().describe("Corporate tax rate"),
  regulatory_risk_premium: z.coerce.number().min(0).describe("Additional discount for regulatory risk"),
});
