import { z } from "zod";

export const MuniBondSchema = z.object({
  bond_name: z.string().describe("Bond name/identifier"),
  face_value: z.coerce.number().positive().describe("Face (par) value"),
  coupon_rate: z.coerce.number().describe("Annual coupon rate (decimal)"),
  coupon_frequency: z.coerce.number().int().positive().describe("Coupons per year"),
  maturity_years: z.coerce.number().positive().describe("Years to maturity"),
  yield_to_maturity: z.coerce.number().describe("Tax-exempt yield to maturity"),
  federal_tax_rate: z.coerce.number().min(0).max(1).describe("Marginal federal tax rate"),
  state_tax_rate: z.coerce.number().min(0).max(1).describe("State tax rate"),
  state_tax_exempt: z.coerce.boolean().describe("Whether bond is exempt from state tax"),
  amt_rate: z.coerce.number().min(0).max(1).optional().describe("AMT rate for private activity bonds"),
  is_private_activity: z.coerce.boolean().describe("Whether this is a private activity bond"),
  purchase_price: z.coerce.number().optional().describe("Purchase price for de minimis analysis"),
  par_call_price: z.coerce.number().optional().describe("Par call price"),
  call_date_years: z.coerce.number().optional().describe("Years until first call date"),
  call_premium: z.coerce.number().optional().describe("Call premium as decimal"),
  credit_rating: z.string().describe("Credit rating (AAA, AA, A, BBB, BB, B)"),
  bond_type: z.enum(["GeneralObligation", "Revenue", "Assessment", "TaxIncrement", "CertificateOfParticipation"]).describe("Municipal bond type"),
  comparable_treasury_yield: z.coerce.number().optional().describe("Comparable Treasury yield"),
  comparable_corporate_yield: z.coerce.number().optional().describe("Comparable corporate yield"),
  day_count: z.string().describe("Day count convention (e.g. 30/360)"),
});

export const MuniAnalysisSchema = z.object({
  analysis_type: z.enum(["GeneralObligation", "RevenueBond", "CreditScore", "Refunding"]).describe("Analysis type"),
  issuer_name: z.string().optional().describe("Issuer name"),
  assessed_valuation: z.coerce.number().optional().describe("Total assessed property valuation"),
  total_direct_debt: z.coerce.number().optional().describe("Total direct debt outstanding"),
  overlapping_debt: z.coerce.number().optional().describe("Overlapping jurisdiction debt"),
  population: z.coerce.number().int().optional().describe("Jurisdiction population"),
  personal_income: z.coerce.number().optional().describe("Total personal income"),
  annual_debt_service: z.coerce.number().optional().describe("Annual debt service payment"),
  general_fund_revenue: z.coerce.number().optional().describe("General fund revenue"),
  general_fund_balance: z.coerce.number().optional().describe("General fund balance"),
  tax_collection_rate: z.coerce.number().optional().describe("Tax collection rate"),
  legal_debt_limit: z.coerce.number().optional().describe("Statutory debt limit"),
  pension_funded_ratio: z.coerce.number().optional().describe("Pension funded ratio"),
  project_name: z.string().optional().describe("Project name (RevenueBond)"),
  gross_revenue: z.coerce.number().optional().describe("Gross revenue"),
  operating_expenses: z.coerce.number().optional().describe("Operating expenses"),
  senior_debt_service: z.coerce.number().optional().describe("Senior-lien debt service"),
  rate_covenant_dscr: z.coerce.number().optional().describe("Rate covenant DSCR"),
  additional_bonds_test_dscr: z.coerce.number().optional().describe("Additional bonds test DSCR"),
  reserve_fund_balance: z.coerce.number().optional().describe("Reserve fund balance"),
  reserve_fund_requirement: z.coerce.number().optional().describe("Reserve fund requirement"),
  days_cash_on_hand: z.coerce.number().int().optional().describe("Days cash on hand"),
  customer_base_count: z.coerce.number().int().optional().describe("Customer base count"),
  top_ten_customer_pct: z.coerce.number().optional().describe("Top-10 customer concentration %"),
  essential_service: z.coerce.boolean().optional().describe("Whether essential service"),
  debt_to_assessed_value: z.coerce.number().optional().describe("Debt to assessed value ratio"),
  debt_per_capita: z.coerce.number().optional().describe("Debt per capita"),
  debt_to_personal_income: z.coerce.number().optional().describe("Debt to personal income ratio"),
  fund_balance_pct: z.coerce.number().optional().describe("Fund balance as pct of revenue"),
  unemployment_rate: z.coerce.number().optional().describe("Unemployment rate"),
  population_growth_5yr: z.coerce.number().optional().describe("5-year population growth rate"),
  median_household_income: z.coerce.number().optional().describe("Median household income"),
  governance_score: z.coerce.number().int().optional().describe("Governance score 1-10"),
  old_bond_outstanding: z.coerce.number().optional().describe("Outstanding par of old bonds"),
  old_coupon_rate: z.coerce.number().optional().describe("Old bond coupon rate"),
  old_remaining_years: z.coerce.number().optional().describe("Remaining years on old bonds"),
  new_coupon_rate: z.coerce.number().optional().describe("New bond coupon rate"),
  new_maturity_years: z.coerce.number().optional().describe("New bond maturity years"),
  issuance_costs_pct: z.coerce.number().optional().describe("Issuance costs as pct of par"),
  escrow_yield: z.coerce.number().optional().describe("Yield on escrow securities"),
  call_date_years: z.coerce.number().optional().describe("Years until first call"),
});
