import { z } from "zod";

export const LetterOfCreditSchema = z.object({
  lc_type: z.enum(["Commercial", "Standby", "Revolving", "BackToBack", "Transferable"]).describe("Type of letter of credit"),
  face_amount: z.coerce.number().positive().describe("Face amount of the LC"),
  currency: z.string().describe("ISO currency code"),
  tenor_days: z.coerce.number().int().positive().describe("Validity in calendar days"),
  issuing_bank_rating: z.string().describe("Issuing bank credit rating"),
  confirming_bank_rating: z.string().optional().describe("Confirming bank credit rating"),
  applicant_country: z.string().describe("Applicant country code (ISO 3166-1)"),
  beneficiary_country: z.string().describe("Beneficiary country code (ISO 3166-1)"),
  issuance_fee_bps: z.coerce.number().min(0).describe("Issuance fee in basis points"),
  confirmation_fee_bps: z.coerce.number().min(0).optional().describe("Confirmation fee in basis points"),
  advising_fee_flat: z.coerce.number().min(0).optional().describe("Flat advising fee"),
  negotiation_fee_bps: z.coerce.number().min(0).optional().describe("Negotiation fee in basis points"),
  amendment_fee_flat: z.coerce.number().min(0).optional().describe("Flat amendment fee"),
  drawing_count: z.coerce.number().int().positive().describe("Expected number of drawings"),
  is_confirmed: z.coerce.boolean().describe("Whether LC is confirmed"),
  is_at_sight: z.coerce.boolean().describe("Sight LC (true) or usance (false)"),
  deferred_payment_days: z.coerce.number().int().optional().describe("Deferred payment days"),
  discount_rate: z.coerce.number().optional().describe("Discount rate for BA discounting"),
  goods_description: z.string().optional().describe("Description of underlying goods"),
});

export const SupplyChainFinanceSchema = z.object({
  analysis_type: z.enum(["ReverseFactoring", "DynamicDiscounting", "Forfaiting", "ExportCredit"]).describe("SCF analysis type"),
  invoice_amount: z.coerce.number().optional().describe("Invoice face value"),
  payment_terms_days: z.coerce.number().int().optional().describe("Original payment terms in days"),
  early_payment_days: z.coerce.number().int().optional().describe("Days for early payment"),
  supplier_cost_of_funds: z.coerce.number().optional().describe("Supplier cost of financing"),
  buyer_credit_spread_bps: z.coerce.number().optional().describe("Buyer credit spread in bps"),
  base_rate: z.coerce.number().optional().describe("Base interest rate (e.g. SOFR)"),
  platform_fee_bps: z.coerce.number().optional().describe("Platform fee in bps"),
  standard_payment_days: z.coerce.number().int().optional().describe("Standard payment term in days"),
  early_payment_day: z.coerce.number().int().optional().describe("Actual early payment day"),
  discount_rate_per_day_bps: z.coerce.number().optional().describe("Discount rate per day early in bps"),
  buyer_opportunity_cost: z.coerce.number().optional().describe("Buyer opportunity cost / WACC"),
  receivable_amount: z.coerce.number().optional().describe("Face value of trade receivable"),
  maturity_days: z.coerce.number().int().optional().describe("Maturity in days"),
  discount_rate: z.coerce.number().optional().describe("Forfaiter discount rate"),
  commitment_fee_bps: z.coerce.number().optional().describe("Commitment fee in bps"),
  is_avalised: z.coerce.boolean().optional().describe("Whether bill is bank-guaranteed"),
  avalising_bank_rating: z.string().optional().describe("Avalising bank credit rating"),
  grace_days: z.coerce.number().int().optional().describe("Grace days added to maturity"),
  contract_value: z.coerce.number().optional().describe("Total contract value"),
  eca_covered_pct: z.coerce.number().optional().describe("ECA coverage percentage"),
  cirr_rate: z.coerce.number().optional().describe("OECD CIRR rate"),
  commercial_rate: z.coerce.number().optional().describe("Commercial market rate"),
  eca_premium_pct: z.coerce.number().optional().describe("ECA premium fee"),
  tenor_years: z.coerce.number().int().optional().describe("Tenor in years"),
  repayment_type: z.enum(["EqualPrincipal", "Annuity"]).optional().describe("Repayment structure"),
  down_payment_pct: z.coerce.number().optional().describe("Down payment percentage"),
});
