#!/usr/bin/env python3
"""Generate plugins/cfa-core/mcp/src/tools.ts from packages/bindings/src/lib.rs.

Mirrors gen-wasm-bindings.py: extracts (function_name, section_title) pairs
and emits a TypeScript module that registers every WASM export as an MCP tool
with a section-derived default description.

Per-tool descriptions can be overridden in DESCRIPTION_OVERRIDES below for
the most-used tools; everything else gets a generic description that includes
the domain (so Claude's tool discovery still finds it via keyword match).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NAPI = REPO / "packages" / "bindings" / "src" / "lib.rs"
OUT = REPO / "plugins" / "cfa-core" / "mcp" / "src" / "tools.ts"

# Hand-written rich descriptions for the most-used tools.
# Everything else falls back to "<domain>: <function name>".
DESCRIPTION_OVERRIDES: dict[str, str] = {
    "calculate_wacc": (
        "Weighted Average Cost of Capital via CAPM. Inputs: risk_free_rate, "
        "equity_risk_premium, beta, cost_of_debt, tax_rate, debt_weight, "
        "equity_weight. Optional: size_premium, country_risk_premium, "
        "specific_risk_premium, unlevered_beta, target_debt_equity (Hamada). "
        "Returns wacc, cost_of_equity, after_tax_cost_of_debt, levered_beta."
    ),
    "build_dcf": (
        "Discounted Cash Flow valuation. Inputs: base_revenue, currency, "
        "revenue_growth_rates[], ebitda_margin, capex_as_pct_revenue, "
        "nwc_as_pct_revenue, tax_rate, wacc, terminal_method (GordonGrowth | "
        "ExitMultiple), terminal_growth_rate, shares_outstanding, net_debt. "
        "Returns enterprise_value, equity_value, per-share value, year-by-year "
        "projections."
    ),
    "comps_analysis": (
        "Trading comparables across peer set. Computes EV/EBITDA, EV/Revenue, "
        "P/E, P/B, PEG mean/median/high/low and derives implied target "
        "valuations."
    ),
    "credit_metrics": (
        "Standard credit metrics: leverage (Debt/EBITDA, Net Debt/EBITDA), "
        "coverage (interest, EBIT, DSCR), liquidity (current, quick), and "
        "synthetic rating (AAA→D)."
    ),
    "debt_capacity": (
        "Maximum sustainable debt at target rating given EBITDA, interest rate, "
        "tax rate, and rating-grade leverage thresholds."
    ),
    "covenant_compliance": (
        "Maintenance covenant headroom test: leverage, coverage, and DSCR vs. "
        "covenant levels, with EBITDA cushion calculation."
    ),
    "altman_zscore": (
        "Altman Z-Score distress prediction (manufacturing/private/non-mfg "
        "models). Returns score and zone (Safe / Grey / Distress)."
    ),
    "build_lbo": (
        "Full LBO model with sources & uses, pro-forma capital structure, "
        "debt schedule, equity returns, and IRR/MOIC waterfall."
    ),
    "calculate_waterfall": (
        "European or American waterfall: return-of-capital → preferred return "
        "→ catch-up → carried interest. Per-LP and GP cash splits."
    ),
    "price_bond": (
        "Bond pricing from yield: clean/dirty price, accrued interest, "
        "DV01. Supports semi-annual / annual / monthly compounding."
    ),
    "price_option": (
        "Option pricing: Black-Scholes (European), CRR binomial (American). "
        "Returns price + Greeks (delta, gamma, theta, vega, rho)."
    ),
}

# Function descriptions to skip (declared elsewhere or wrapper-shaped).
SKIP: set[str] = {
    "scenario_analysis",  # Wrapper-shaped, takes extra args. v0.3 work item.
}

# Friendly aliases preserved from v0.1 so existing skills/commands keep working.
# Each entry registers an additional tool name pointing to the same WASM export.
LEGACY_ALIASES: dict[str, str] = {
    "wacc_calculator": "calculate_wacc",
    "dcf_model": "build_dcf",
}

NAPI_RE = re.compile(
    r"#\[napi\]\s+"
    r"pub\s+fn\s+(\w+)\s*\(\s*input_json\s*:\s*String\s*\)\s*->\s*NapiResult<String>\s*\{\s*"
    r"let\s+input\s*:\s*([\w:]+)\s*=\s*"
    r"serde_json::from_str\(\s*&input_json\s*\)\s*\.map_err\(\s*to_napi_error\s*\)\s*\?\s*;\s*"
    r"let\s+output\s*=\s*"
    r"([\w:]+)\s*\(\s*&input\s*,?\s*\)\s*\.map_err\(\s*to_napi_error\s*\)\s*\?\s*;\s*"
    r"serde_json::to_string\(\s*&output\s*\)\s*\.map_err\(\s*to_napi_error\s*\)\s*"
    r"\}",
    re.DOTALL,
)

SECTION_RE = re.compile(
    r"// -+\s*\n// ([^\n]+)\s*\n// -+",
    re.MULTILINE,
)


def humanise(name: str) -> str:
    """`calculate_credit_metrics` → `Calculate credit metrics`."""
    return name.replace("_", " ").capitalize()


HEADER = """/**
 * cfa-core MCP tool registry.
 *
 * GENERATED FROM packages/bindings/src/lib.rs by scripts/gen-mcp-tools.py.
 * Do not edit by hand — re-run the generator if NAPI bindings change.
 *
 * Each entry registers one WASM export as an MCP tool. If a per-tool zod
 * schema exists in TOOL_SCHEMAS (generated by scripts/gen-zod-schemas.py),
 * it's used directly so Claude sees typed field hints. Otherwise we fall
 * back to the passthrough record schema and let Rust serde validate.
 *
 * Profile telemetry (T4.3): every tool call increments PROFILE counters
 * for call-count, total wall time, total compute time (from the Rust-side
 * `metadata.computation_time_us` field), and last-error string. Surfaced
 * via the `cfa_profile` MCP tool registered at the end of registerAllTools.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { TOOL_SCHEMAS } from "./schemas.js";

type WasmExports = Record<string, (json: string) => string>;

interface ToolStats {
  calls: number;
  errors: number;
  wall_us_total: number;
  compute_us_total: number;
  last_error?: string;
}

const PROFILE = new Map<string, ToolStats>();
const SESSION_STARTED_AT = Date.now();

function bumpProfile(
  name: string,
  wallUs: number,
  computeUs: number | null,
  errorMessage?: string,
) {
  let stats = PROFILE.get(name);
  if (!stats) {
    stats = { calls: 0, errors: 0, wall_us_total: 0, compute_us_total: 0 };
    PROFILE.set(name, stats);
  }
  stats.calls++;
  stats.wall_us_total += wallUs;
  if (computeUs !== null) stats.compute_us_total += computeUs;
  if (errorMessage) {
    stats.errors++;
    stats.last_error = errorMessage;
  }
}

function extractComputeUs(jsonResult: string): number | null {
  // Cheap regex parse — avoids JSON.parse cost for hot path. The Rust output
  // envelope always emits `"computation_time_us": <int>` inside metadata.
  const m = /"computation_time_us"\s*:\s*(\d+)/.exec(jsonResult);
  return m ? parseInt(m[1], 10) : null;
}

const passthroughShape = {
  input: z
    .record(z.any())
    .describe("Tool inputs as a JSON object — see tool description for fields"),
};

function wrap(jsonResult: string) {
  return { content: [{ type: "text" as const, text: jsonResult }] };
}

function shapeFor(name: string, exportName: string) {
  // Prefer the schema registered under the public tool name; fall back to the
  // underlying WASM export name (so legacy aliases inherit their target's schema).
  const schema = TOOL_SCHEMAS[name] ?? TOOL_SCHEMAS[exportName];
  if (schema) {
    return { input: schema };
  }
  return passthroughShape;
}

function registerTool(
  server: McpServer,
  wasm: WasmExports,
  name: string,
  description: string,
  exportName: string = name,
) {
  const fn = wasm[exportName];
  if (typeof fn !== "function") {
    // Defensive: WASM was built without this export. Skip with a warning so
    // partial WASM builds don't crash the whole server.
    console.warn(`[cfa-core] WASM export missing: ${exportName} — skipping`);
    return;
  }
  server.tool(
    name,
    description,
    shapeFor(name, exportName),
    async (params: { input: Record<string, unknown> }) => {
      const t0 = process.hrtime.bigint();
      try {
        const result = fn(JSON.stringify(params.input ?? {}));
        const wallUs = Number((process.hrtime.bigint() - t0) / 1000n);
        bumpProfile(name, wallUs, extractComputeUs(result));
        return wrap(result);
      } catch (err) {
        const wallUs = Number((process.hrtime.bigint() - t0) / 1000n);
        const message = err instanceof Error ? err.message : String(err);
        bumpProfile(name, wallUs, null, message);
        return {
          content: [{ type: "text" as const, text: `error: ${message}` }],
          isError: true,
        };
      }
    },
  );
}

function registerProfileTool(server: McpServer) {
  server.tool(
    "cfa_profile",
    "Per-session telemetry: call counts, total wall time, total Rust compute time, and overhead per tool. Returns the top-N by total wall time. Useful before iterating an expensive tool (e.g. monte_carlo_dcf) in a sensitivity grid.",
    {
      top: z
        .number()
        .int()
        .min(1)
        .max(500)
        .optional()
        .describe("Maximum number of tools to report (default: 20, sorted by total wall time desc)"),
      sort_by: z
        .enum(["wall", "compute", "calls", "overhead"])
        .optional()
        .describe("Sort key (default: wall)"),
    },
    async (params) => {
      const top = params.top ?? 20;
      const sort = params.sort_by ?? "wall";
      const entries = Array.from(PROFILE.entries()).map(([name, s]) => ({
        tool: name,
        calls: s.calls,
        errors: s.errors,
        wall_us_total: s.wall_us_total,
        compute_us_total: s.compute_us_total,
        overhead_us_total: Math.max(0, s.wall_us_total - s.compute_us_total),
        avg_wall_us: s.calls ? Math.round(s.wall_us_total / s.calls) : 0,
        avg_compute_us: s.calls ? Math.round(s.compute_us_total / s.calls) : 0,
        last_error: s.last_error,
      }));
      const sortKey: Record<typeof sort, (e: typeof entries[number]) => number> = {
        wall: (e) => e.wall_us_total,
        compute: (e) => e.compute_us_total,
        calls: (e) => e.calls,
        overhead: (e) => e.overhead_us_total,
      };
      entries.sort((a, b) => sortKey[sort](b) - sortKey[sort](a));
      const report = {
        session_uptime_ms: Date.now() - SESSION_STARTED_AT,
        unique_tools_called: entries.length,
        total_calls: entries.reduce((acc, e) => acc + e.calls, 0),
        total_errors: entries.reduce((acc, e) => acc + e.errors, 0),
        sort_by: sort,
        top: entries.slice(0, top),
      };
      return {
        content: [{ type: "text" as const, text: JSON.stringify(report, null, 2) }],
      };
    },
  );
}

export function registerAllTools(server: McpServer, wasm: WasmExports): number {
  let count = 0;
"""

FOOTER = """
  // --- Built-in: cfa_profile (T4.3 telemetry) ---
  registerProfileTool(server); count++;

  return count;
}
"""


def main() -> int:
    src = NAPI.read_text()

    matches: list[tuple[int, str, tuple]] = []
    for m in NAPI_RE.finditer(src):
        matches.append((m.start(), "tool", (m.group(1),)))
    for m in SECTION_RE.finditer(src):
        matches.append((m.start(), "section", (m.group(1).strip(),)))
    matches.sort(key=lambda t: t[0])

    out: list[str] = [HEADER]
    current_section = "Uncategorised"
    tool_count = 0

    for _, kind, payload in matches:
        if kind == "section":
            (title,) = payload
            current_section = title
            out.append(f'\n  // --- {title} ---\n')
        else:
            (name,) = payload
            if name in SKIP:
                continue
            description = DESCRIPTION_OVERRIDES.get(
                name,
                f"{current_section}: {humanise(name)}.",
            )
            # Escape backticks for template literal safety.
            esc = description.replace("\\", "\\\\").replace("`", "\\`")
            out.append(
                f'  registerTool(server, wasm, "{name}", `{esc}`); count++;\n'
            )
            tool_count += 1

    if LEGACY_ALIASES:
        out.append("\n  // --- Legacy v0.1 aliases (kept for skill/command compatibility) ---\n")
        for alias, target in LEGACY_ALIASES.items():
            description = DESCRIPTION_OVERRIDES.get(
                alias,
                DESCRIPTION_OVERRIDES.get(target, f"Alias for {target}"),
            )
            esc = description.replace("\\", "\\\\").replace("`", "\\`")
            out.append(
                f'  registerTool(server, wasm, "{alias}", `{esc}`, "{target}"); count++;\n'
            )

    out.append(FOOTER)
    OUT.write_text("".join(out))

    print(f"Wrote {OUT.relative_to(REPO)}")
    print(f"  Tools registered: {tool_count}")
    print(f"  Aliases         : {len(LEGACY_ALIASES)}")
    print(f"  Skipped         : {len(SKIP)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
